---
- name: Test Kubernetes connection
  hosts: localhost
  gather_facts: false
  tasks:
    - name: List files in /tmp
      ansible.builtin.command: ls -l /tmp
      register: tmp_files
    
    - name: Show tmp files
      ansible.builtin.debug:
        var: tmp_files.stdout_lines
        - name: Get all namespaces
          kubernetes.core.k8s_info:
            kind: Namespace
    
    - name: Print environment variables
      ansible.builtin.shell: env
      register: env_output
    
    - name: Show env output
      ansible.builtin.debug:
        var: env_output.stdout_lines

    - name: List files in /runner/secrets
      ansible.builtin.command: ls -l /runner/secrets
      register: secrets_files
    
    - name: Show secrets files
      ansible.builtin.debug:
        var: secrets_files.stdout_lines

    - name: Get all namespaces
      kubernetes.core.k8s_info:
        kind: Namespace
        kubeconfig: /runner/kubeconfig
    
    - name: Get all namespaces
      kubernetes.core.k8s_info:
        kind: Namespace
        kubeconfig: /tmp/kubeconfig    # Path inside container where kubeconfig is mounted
      register: namespaces

    - debug:
        var: namespaces.resources
