---
- name: Debug Kubernetes connectivity in AWX EE
  hosts: localhost
  gather_facts: false
  vars:
    kubeconfig_path: "/path/to/kubeconfig"   # Adjust to where your kubeconfig is mounted in EE
    apiserver_url: "https://10.184.146.142:33443"

  tasks:
    - name: Check if KUBECONFIG file exists
      ansible.builtin.stat:
        path: "{{ kubeconfig_path }}"
      register: kubeconfig_stat

    - name: Show KUBECONFIG file info
      ansible.builtin.debug:
        var: kubeconfig_stat

    - name: List kubeconfig file contents (first 20 lines)
      ansible.builtin.command:
        cmd: head -20 "{{ kubeconfig_path }}"
      when: kubeconfig_stat.stat.exists

    - name: Run kubectl get ns using the kubeconfig explicitly
      ansible.builtin.command:
        cmd: kubectl get ns --kubeconfig "{{ kubeconfig_path }}"
      register: kubectl_output
      failed_when: kubectl_output.rc != 0
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"
      when: kubeconfig_stat.stat.exists

    - name: Show kubectl get ns output
      ansible.builtin.debug:
        var: kubectl_output.stdout_lines
      when: kubectl_output is defined

    - name: Test API server connectivity with curl
      ansible.builtin.command:
        cmd: curl -k -m 10 "{{ apiserver_url }}/version"
      register: curl_output
      failed_when: curl_output.rc != 0

    - name: Show curl output
      ansible.builtin.debug:
        var: curl_output.stdout_lines

    - name: Try k8s_info module to get namespaces (skip if kubeconfig missing)
      kubernetes.core.k8s_info:
        kind: Namespace
        kubeconfig: "{{ kubeconfig_path }}"
      register: k8s_info_output
      when: kubeconfig_stat.stat.exists

    - name: Show namespaces from k8s_info
      ansible.builtin.debug:
        var: k8s_info_output.resources
      when: k8s_info_output is defined
