---
- name: Test Kubernetes connection
  hosts: localhost
  gather_facts: false
  tasks:

    - name: Check kube config
      hosts: localhost
      gather_facts: false
      tasks:
    
    - name: Run kubectl
      ansible.builtin.command:
        cmd: "kubectl get ns"
        
    - name: Get all namespaces
      kubernetes.core.k8s_info:
        kind: Namespace
    
    - name: Test connectivity to Kubernetes API
      ansible.builtin.shell: |
        curl -k https://10.184.146.1:33443/version
      register: curl_result
    
    - debug:
        var: curl_result.stdout
    
    - name: Show /tmp/kubeconfig content
      ansible.builtin.command:
        cmd: cat /tmp/kubeconfig
      register: kubeconfig_content
      ignore_errors: yes
    
    - name: Display kubeconfig content
      ansible.builtin.debug:
        var: kubeconfig_content.stdout_lines
    
    - name: List files in /tmp
      ansible.builtin.command: ls -l /tmp
      register: tmp_files

    - name: Show tmp files
      ansible.builtin.debug:
        var: tmp_files.stdout_lines

    - name: Print environment variables
      ansible.builtin.shell: env
      register: env_output

    - name: Show env output
      ansible.builtin.debug:
        var: env_output.stdout_lines

    - name: List files in /runner/secrets
      ansible.builtin.command: ls -l /runner/secrets
      register: secrets_files

    - name: Show secrets files
      ansible.builtin.debug:
        var: secrets_files.stdout_lines

    - name: Get all namespaces (using /runner/kubeconfig)
      kubernetes.core.k8s_info:
        kind: Namespace
        kubeconfig: /runner/kubeconfig
      register: namespaces_runner_kubeconfig
      ignore_errors: yes

    - name: Get all namespaces (using /tmp/kubeconfig)
      kubernetes.core.k8s_info:
        kind: Namespace
        kubeconfig: /tmp/kubeconfig
      register: namespaces_tmp_kubeconfig
      ignore_errors: yes

    - name: Show namespaces result from /runner/kubeconfig
      debug:
        var: namespaces_runner_kubeconfig.resources

    - name: Show namespaces result from /tmp/kubeconfig
      debug:
        var: namespaces_tmp_kubeconfig.resources
